describe('test search for listigns', () => {
  beforeEach(() => {
    cy.resetDatabase()
    cy.initializeTestData()
    cy.visit('http://localhost:5173/register')
    cy.get('input[name="username"]').type('newuser')
    cy.get('input[name="password"]').type('test')
    cy.get('button[type="submit"]').click()
    cy.visit('http://localhost:5173/login')
    cy.get('input[name="username"]').type('newuser')
    cy.get('input[name="password"]').type('test')
    cy.get('button[type="submit"]').click()
  })

  it('Search for a specific listing', () => {
    cy.get('input[name="findigo-search"]').type('en{enter}')
    cy.contains('En rask bil').should('exist')
    cy.contains('En annen testbil').should('exist')
    cy.contains('En annen testhus').should('exist')
    cy.get(':nth-child(2) > .category-link').click()
    cy.contains('En rask bil').should('exist')
    cy.contains('En annen testbil').should('exist')
    cy.get(':nth-child(3) > .category-link').click()
    cy.contains('En annen testhus').should('exist')
    cy.get(':nth-child(1) > .category-link').click()
    cy.get('[placeholder="min"]').type('10')
    cy.get('[placeholder="max"]').type('11000')
    cy.get('.price-inputs > .apply-button').click()
    cy.get('.dates-inputs > input').type('2004-04-04')
    cy.get('.dates-inputs > .apply-button').click()
    cy.contains('En rask bil').should('exist')
    cy.contains('En annen testbil').should('exist')
  })
})
